### ISSUE TITLE
Mouse over does not change glyph in legend

### ISSUE THREAD

**Issue by dkammer** [visualengineers/glyphboard#24]
In specific datasets, the glyph in the configuration menu was not updated using selection mode on LOD 2.

**Comment by mandyTUD** [comment]
selected glyphboard should be also shown in legend in zoom&panning mode (currently just in selection mode)

**Comment by mandyTUD** [comment]
e.g. in datasets with +8.000 items

**Comment by mandyTUD** [comment]
Was not a problem in Glyphboard. 
In that specific dataset the features were not normalized what caused the error.
