### ISSUE TITLE
Keep configuration when loading splitscreen or new positions

### ISSUE THREAD

**Issue by dkammer** [visualengineers/glyphboard#9]
Configuration is reset when loading different data set options.

Edit: Keep feature configuration when PA or V is changed.

**Comment by kristopheles** [comment]
It keeps the configuration when data set version, the positioning algorithm or the context feature is changed. 
But there is one problem. If you change something for the data set in the single screen or the left side of the split screen mode, the dashboard is redrawn and this resets the visible filter settings.
@dkammer Any ideas to prevent the redraw of the dashboard?
